### PR TITLE
Added docker-compose

### PR DESCRIPTION
**Pull request by lqb**
- "docker-compose up -d" should be running without any pre configuration

### CODE REVIEW

**Comment by awlx** [comment]
I am not a fan of the `sed` move ... either we provide a `wgkex.yaml.docker` or something or leave it to manual adjustment.

**Comment by lqb** [comment]
Me either, but better than crushing containers.

**Comment by awlx** [comment]
So add a working wgkex.yaml.docker and get rid of the sed

**Comment by lqb** [comment]
No. I just added an entrypoint

**Comment by awlx** [comment]
But do hardcoded FFMUC domains make any sense? That's a project for everyone not just us.

**Comment by lqb** [comment]
What do you mean?

**Comment by lqb** [comment]
You can overwrite them with environment variables.

**Pull request merged**
