### PR TITLE
Handle NetlinkDumpInterrupted, fix worker metrics going stale after exceptions

### PR DESCRIPTION
**Pull request by DasSkelett**
This hardens the connected peers metrics collection threads of the worker by handling exceptions gracefully, instead of crashing the thread, which caused the metrics to go stale after time, domain after domain.

This also fixes one particular cause for exceptions, `pyroute2.netlink.exceptions.NetlinkDumpInterrupted`, which apparently is an "expected" exception, being thrown whenever the base data is changed while the kernel returns it. This signals the userspace application that the data might be useless and the netlink request should be retried.
This probably happens when a new peer is added while asking for the interface data.

```
Mar 28 22:25:07 gw04.in.ffmuc.net wgkex[3226905]: Exception in thread Thread-31:
Mar 28 22:25:07 gw04.in.ffmuc.net wgkex[3226905]: Traceback (most recent call last):
Mar 28 22:25:07 gw04.in.ffmuc.net wgkex[3226905]:   File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
Mar 28 22:25:07 gw04.in.ffmuc.net wgkex[3226905]:     self.run()
Mar 28 22:25:07 gw04.in.ffmuc.net wgkex[3226905]:   File "/usr/lib/python3.8/threading.py", line 870, in run
Mar 28 22:25:07 gw04.in.ffmuc.net wgkex[3226905]:     self._target(*self._args, **self._kwargs)
Mar 28 22:25:07 gw04.in.ffmuc.net wgkex[3226905]:   File "/srv/wgkex/wgkex/wgkex/worker/mqtt.py", line 209, in publish_metrics_loop
Mar 28 22:25:07 gw04.in.ffmuc.net wgkex[3226905]:     publish_metrics(client, topic, domain)
Mar 28 22:25:07 gw04.in.ffmuc.net wgkex[3226905]:   File "/srv/wgkex/wgkex/wgkex/worker/mqtt.py", line 230, in publish_metrics
Mar 28 22:25:07 gw04.in.ffmuc.net wgkex[3226905]:     peer_count = get_connected_peers_count(iface)
Mar 28 22:25:07 gw04.in.ffmuc.net wgkex[3226905]:   File "/srv/wgkex/wgkex/wgkex/worker/netlink.py", line 226, in get_connected_peers_count
Mar 28 22:25:07 gw04.in.ffmuc.net wgkex[3226905]:     msgs = wg.info(wg_interface)
Mar 28 22:25:07 gw04.in.ffmuc.net wgkex[3226905]:   File "/srv/wgkex/wgkex/venv/lib/python3.8/site-packages/pyroute2/netlink/generic/wireguard.py", line 274, in info
Mar 28 22:25:07 gw04.in.ffmuc.net wgkex[3226905]:     return self.nlm_request(
Mar 28 22:25:07 gw04.in.ffmuc.net wgkex[3226905]:   File "/srv/wgkex/wgkex/venv/lib/python3.8/site-packages/pyroute2/netlink/nlsocket.py", line 870, in nlm_request
Mar 28 22:25:07 gw04.in.ffmuc.net wgkex[3226905]:     return tuple(self._genlm_request(*argv, **kwarg))
Mar 28 22:25:07 gw04.in.ffmuc.net wgkex[3226905]:   File "/srv/wgkex/wgkex/venv/lib/python3.8/site-packages/pyroute2/netlink/generic/__init__.py", line 126, in nlm_request
Mar 28 22:25:07 gw04.in.ffmuc.net wgkex[3226905]:     return tuple(super().nlm_request(*argv, **kwarg))
Mar 28 22:25:07 gw04.in.ffmuc.net wgkex[3226905]:   File "/srv/wgkex/wgkex/venv/lib/python3.8/site-packages/pyroute2/netlink/nlsocket.py", line 1257, in nlm_request
Mar 28 22:25:07 gw04.in.ffmuc.net wgkex[3226905]:     raise defer
Mar 28 22:25:07 gw04.in.ffmuc.net wgkex[3226905]: pyroute2.netlink.exceptions.NetlinkDumpInterrupted: (-1, 'dump interrupted')

```

We retry it once, and if it still doesn't succeed we just ignore it, don't publish new metrics data and wait for the next loop iteration.

We can also think about additionally doing our own mutex locking across all places where we read/write wg interface data; especially if this happens more during e.g. mass reconnects, where up-to-date peer numbers would be important as well. I'll monitor this and see if the additional complexity is needed/worth it.

### CODE REVIEW

**Comment by T0biii** [comment]
`ModuleNotFoundError: No module named 'pyroute2.netlink.exceptions'; 'pyroute2.netlink' is not a package` - https://github.com/freifunkMUC/wgkex/actions/runs/8474567354/job/23221187018?pr=137#step:4:61
i guess something in https://github.com/freifunkMUC/wgkex/blob/main/wgkex/worker/netlink_test.py needs to be adjusted as well?

**Comment by T0biii** [comment]
for what is coverage/coveralls?

**Comment by DasSkelett** [comment]
> for what is coverage/coveralls?

It's a test coverage checker, basically it complains there are a handful of new lines which are not tested by unit tests.
I might have an idea for an easy test to add.

**Comment by DasSkelett** [comment]
Well this was a bit of a fight with the mock library, but got there in the end. This should be ready now.

**Review by T0biii — APPROVED** [review]
LGTM (catching Exceptions)

**Pull request merged**
